/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarChart: typeof import('./src/components/home/CarChart.vue')['default']
    EnergyChart: typeof import('./src/components/home/EnergyChart.vue')['default']
    Equipment: typeof import('./src/components/home/Equipment.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PassengerChart: typeof import('./src/components/home/PassengerChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./src/components/home/services.vue')['default']
    ShopChart: typeof import('./src/components/home/ShopChart.vue')['default']
    VueCountTo: typeof import('./src/components/CountTo/vue-countTo.vue')['default']
  }
}
